name = "SimpleTextAdventure"
uuid = "f7fe5873-c891-4e00-a3c3-ac9d0bca5d17"
authors = ["Siddharth Bhatia <sidb60200@gmail.com>", "contributors"]
version = "0.1.0"

[deps]
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
julia = "1"
YAML = "0.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
